name: Prebuild for Code Spaces

on:
  push:
    branches:
      - main

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
      node-version: 16

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pre-build tasks
      run: |
        # Add any pre-build tasks here, e.g., running tests or building assets

    - name: Cache prebuild artifacts
      uses: actions/cache@v2
      with:
        path: |
          .venv
          .cache
        key: prebuild-${{ hashFiles('requirements.txt') }}
